import React, { createContext, useContext, useState, ReactNode } from 'react';

interface LanguageContextType {
  language: 'ar' | 'en';
  setLanguage: (lang: 'ar' | 'en') => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  ar: {
    // Navigation
    'home': 'الرئيسية',
    'search': 'البحث',
    'dashboard': 'لوحة التحكم',
    'admin': 'الإدارة',
    'login': 'تسجيل الدخول',
    'logout': 'تسجيل الخروج',
    
    // Homepage
    'hero.title': 'احجز رحلتك على قطارات السودان',
    'hero.subtitle': 'استكشف السودان بأمان وراحة مع شبكة السكك الحديدية السودانية',
    'book.your.journey': 'احجز رحلتك',
    'my.bookings': 'حجوزاتي',
    'view.manage.trips': 'عرض وإدارة الرحلات',
    'train.status': 'حالة القطار',
    'check.live.status': 'تحقق من الحالة المباشرة',
    'customer.support': 'خدمة العملاء',
    '24.7.support': 'دعم على مدار الساعة',
    'need.help': 'تحتاج مساعدة؟',
    'contact.support.team': 'تواصل مع فريق الدعم الخاص بنا',
    'call.us': 'اتصل بنا',
    'email.us': 'راسلنا',
    'live.chat': 'محادثة مباشرة',
    'available.24.7': 'متاح 24/7',
    'from': 'من',
    'to': 'إلى',
    'date': 'التاريخ',
    'passengers': 'المسافرون',
    'class': 'الدرجة',
    'search.trains': 'البحث عن القطارات',
    'why.choose.atbara.rail': 'لماذا تختار قطارات عطبرة؟',
    'experience.future.travel': 'اختبر مستقبل السفر مع خدماتنا الحديثة والفعالة والمريحة',
    'popular.routes': 'الوجهات الأكثر شعبية',
    'discover.most.traveled': 'اكتشف الوجهات الأكثر سفراً عبر جمهورية السودان',
    'safe.secure': 'آمن ومضمون',
    'modern.safety.systems': 'أنظمة أمان حديثة وحجز آمن',
    'on.time.performance': 'الالتزام بالمواعيد',
    'reliable.schedules': 'جداول موثوقة وخدمات دقيقة',
    'comfort.quality': 'راحة وجودة',
    'premium.seats': 'مقاعد فاخرة وخدمة ممتازة',
    'award.winning': 'حائز على جوائز',
    'recognized.excellence': 'معترف به للتميز في النقل',
    
    // Search Results
    'available.trains': 'القطارات المتاحة',
    'departure': 'المغادرة',
    'arrival': 'الوصول',
    'duration': 'المدة',
    'price': 'السعر',
    'book.now': 'احجز الآن',
    'no.trains': 'لا توجد قطارات متاحة',
    'trains.found': 'قطار متاح',
    'modify.search': 'تعديل البحث',
    'filters': 'المرشحات',
    'all.classes': 'جميع الدرجات',
    'price.range.sar': 'نطاق السعر (ريال)',
    'sort.by': 'ترتيب حسب',
    'departure.time': 'وقت المغادرة',
    'seats.available': 'مقعد متاح',
    'per.person': 'للشخص الواحد',
    
    // Booking
    'passenger.info': 'معلومات المسافر',
    'full.name': 'الاسم الكامل',
    'full.name.arabic': 'الاسم الكامل بالعربية',
    'full.name.english': 'الاسم الكامل بالإنجليزية',
    'id.number': 'رقم الهوية',
    'id.passport.number': 'رقم الهوية/جواز السفر',
    'birth.date': 'تاريخ الميلاد',
    'gender': 'الجنس',
    'male': 'ذكر',
    'female': 'أنثى',
    'nationality': 'الجنسية',
    'optional': 'اختياري',
    'seat.selection': 'اختيار المقعد',
    'selected.seat': 'المقعد المختار',
    'auto.select.seat': 'اختيار تلقائي للمقعد',
    'add.another.passenger': 'إضافة مسافر آخر',
    'add.passenger': 'إضافة مسافر',
    'payment.summary': 'ملخص الدفع',
    'choose.payment.method': 'اختر طريقة الدفع',
    'credit.debit.card': 'بطاقة ائتمان/خصم',
    'mobile.payment': 'الدفع عبر الهاتف',
    'bank.transfer': 'التحويل المصرفي',
    'pay.via.bank': 'ادفع عن طريق البنك',
    'agree.terms.conditions': 'أوافق على الشروط والأحكام',
    'continue.payment': 'متابعة الدفع',
    'booking.summary': 'ملخص الحجز',
    'route': 'المسار',
    'ticket.price': 'سعر التذكرة',
    'service.fee': 'رسوم الخدمة',
    'total': 'المجموع',
    'passenger.information': 'معلومات المسافر',
    'email': 'البريد الإلكتروني',
    'phone': 'رقم الهاتف',
    'available': 'متاح',
    'occupied': 'محجوز',
    'selected': 'مختار',
    'payment': 'الدفع',
    'card.number': 'رقم البطاقة',
    'expiry.date': 'تاريخ الانتهاء',
    'cardholder.name': 'اسم حامل البطاقة',
    'booking.confirmed': 'تم تأكيد الحجز!',
    'ticket.booked.successfully': 'تم حجز تذكرتك بنجاح. ستتلقى رسالة تأكيد قريباً.',
    'booking.reference': 'رقم الحجز',
    'scan.at.station': 'امسح في المحطة',
    'whatsapp.us': 'واتساب',
    'secure.payment.guaranteed': 'دفع آمن ومضمون',
    'view.my.trips': 'عرض رحلاتي',
    'book.another.trip': 'حجز رحلة أخرى',
    
    // Dashboard
    'my.trips': 'رحلاتي',
    'upcoming': 'القادمة',
    'past': 'السابقة',
    'download.ticket': 'تحميل التذكرة',
    'cancel.trip': 'إلغاء الرحلة',
    'reschedule': 'إعادة جدولة',
    'welcome.back': 'مرحباً بعودتك',
    'no.upcoming.trips': 'لا توجد رحلات قادمة',
    'no.past.trips': 'لا توجد رحلات سابقة',
    'e.ticket': 'التذكرة الإلكترونية',
    'scan.qr.code': 'امسح رمز الاستجابة السريعة في المحطة',
    'booking.ref': 'رقم الحجز:',
    'train': 'القطار:',
    'seat': 'المقعد:',
    'download.pdf': 'تحميل PDF',
    
    // Admin Panel
    'admin.dashboard': 'لوحة تحكم الإدارة',
    'manage.train.booking.system': 'إدارة نظام حجز القطارات',
    'overview': 'نظرة عامة',
    'trains': 'القطارات',
    'bookings': 'الحجوزات',
    'users': 'المستخدمون',
    'total.bookings': 'إجمالي الحجوزات',
    'total.revenue': 'إجمالي الإيرادات',
    'active.trains': 'القطارات النشطة',
    'total.users': 'إجمالي المستخدمين',
    'recent.activity': 'النشاط الأخير',
    'new.booking': 'حجز جديد',
    'payment.received': 'تم استلام الدفع',
    'train.schedule.updated': 'تم تحديث جدول القطار',
    'new.user.registration': 'تسجيل مستخدم جديد',
    'train.routes': 'مسارات القطارات',
    'add.route': 'إضافة مسار',
    'schedule': 'الجدول',
    'capacity': 'السعة',
    'actions': 'الإجراءات',
    'recent.bookings': 'الحجوزات الأخيرة',
    'confirmed': 'مؤكد',
    'cancelled': 'ملغي',
    'user.management': 'إدارة المستخدمين',
    'joined': 'انضم:',
    'trips': 'رحلات',
    'access.denied': 'تم رفض الوصول',
    'no.permission': 'ليس لديك إذن للوصول إلى هذه المنطقة.',
    
    // Common
    'loading': 'جاري التحميل...',
    'error': 'خطأ',
    'success': 'تم بنجاح',
    'cancel': 'إلغاء',
    'confirm': 'تأكيد',
    'save': 'حفظ',
    'edit': 'تعديل',
    'delete': 'حذف',
    'submit': 'إرسال',
    'back': 'رجوع',
    'next': 'التالي',
    'previous': 'السابق',
    'close': 'إغلاق',
    'select': 'اختر',
    'min': 'أدنى',
    'max': 'أقصى',
    'minutes.ago': 'دقائق مضت',
    'hour.ago': 'ساعة مضت',
    'hours.ago': 'ساعات مضت',
    
    // Cities and Places
    'atbara.rail': 'قطارات عطبرة',
    'khartoum': 'الخرطوم',
    'atbara': 'عطبرة',
    'port.sudan': 'بورت سودان',
    'kassala': 'كسلا',
    'wad.medani': 'ود مدني',
    'nyala': 'نيالا',
    'el.obeid': 'الأبيض',
    'dongola': 'دنقلا',
    'sennar': 'سنار',
    
    // Nationalities
    'sudan': 'جمهورية السودان',
    'egypt': 'جمهورية مصر العربية',
    'ethiopia': 'إثيوبيا',
    'eritrea': 'إريتريا',
    'chad': 'تشاد',
    'libya': 'ليبيا',
    'south.sudan': 'جنوب السودان',
    'other': 'أخرى',
    
    // Train Classes
    'economy': 'الاقتصادية',
    'business': 'رجال الأعمال',
    'vip': 'كبار الشخصيات',
    
    // Time and Duration
    'from.sar': 'من',
    'sdg': 'جنيه سوداني',
    'duration.hours': 'ساعات',
    'duration.minutes': 'دقائق'
  },
  en: {
    // Navigation
    'home': 'Home',
    'search': 'Search',
    'dashboard': 'Dashboard',
    'admin': 'Admin',
    'login': 'Login',
    'logout': 'Logout',
    
    // Homepage
    'hero.title': 'Book Your Train Journey in Sudan',
    'hero.subtitle': 'Discover Sudan with ease and comfort on Sudan Railways',
    'book.your.journey': 'Book Your Journey',
    'my.bookings': 'My Bookings',
    'view.manage.trips': 'View and manage trips',
    'train.status': 'Train Status',
    'check.live.status': 'Check live status',
    'customer.support': 'Customer Support',
    '24.7.support': '24/7 Support',
    'need.help': 'Need Help?',
    'contact.support.team': 'Contact our support team',
    'call.us': 'Call Us',
    'email.us': 'Email Us',
    'live.chat': 'Live Chat',
    'available.24.7': 'Available 24/7',
    'from': 'From',
    'to': 'To',
    'date': 'Date',
    'passengers': 'Passengers',
    'class': 'Class',
    'search.trains': 'Search Trains',
    'why.choose.atbara.rail': 'Why Choose Atbara Rail?',
    'experience.future.travel': 'Experience the future of travel with our modern, efficient, and comfortable services',
    'popular.routes': 'Popular Routes',
    'discover.most.traveled': 'Discover the most traveled destinations across Sudan',
    'safe.secure': 'Safe & Secure',
    'modern.safety.systems': 'Modern safety systems and secure booking',
    'on.time.performance': 'On-Time Performance',
    'reliable.schedules': 'Reliable schedules and punctual services',
    'comfort.quality': 'Comfort & Quality',
    'premium.seats': 'Premium seating and excellent service',
    'award.winning': 'Award Winning',
    'recognized.excellence': 'Recognized for excellence in transportation',
    
    // Search Results
    'available.trains': 'Available Trains',
    'departure': 'Departure',
    'arrival': 'Arrival',
    'duration': 'Duration',
    'price': 'Price',
    'book.now': 'Book Now',
    'no.trains': 'No trains available',
    'trains.found': 'trains found',
    'modify.search': 'Modify Search',
    'filters': 'Filters',
    'all.classes': 'All Classes',
    'price.range.sdg': 'Price Range (SDG)',
    'sort.by': 'Sort By',
    'departure.time': 'Departure Time',
    'seats.available': 'seats available',
    'per.person': 'per person',
    
    // Booking
    'passenger.info': 'Passenger Information',
    'full.name': 'Full Name',
    'full.name.arabic': 'Full Name in Arabic',
    'full.name.english': 'Full Name in English',
    'id.number': 'ID Number',
    'id.passport.number': 'ID/Passport Number',
    'birth.date': 'Birth Date',
    'gender': 'Gender',
    'male': 'Male',
    'female': 'Female',
    'nationality': 'Nationality',
    'optional': 'Optional',
    'seat.selection': 'Seat Selection',
    'selected.seat': 'Selected Seat',
    'auto.select.seat': 'Auto Select Seat',
    'add.another.passenger': 'Add Another Passenger',
    'add.passenger': 'Add Passenger',
    'payment.summary': 'Payment Summary',
    'choose.payment.method': 'Choose Payment Method',
    'credit.debit.card': 'Credit/Debit Card',
    'mobile.payment': 'Mobile Payment',
    'bank.transfer': 'Bank Transfer',
    'pay.via.bank': 'Pay via Bank',
    'agree.terms.conditions': 'I agree to terms and conditions',
    'continue.payment': 'Continue to Payment',
    'booking.summary': 'Booking Summary',
    'route': 'Route',
    'ticket.price': 'Ticket Price',
    'service.fee': 'Service Fee',
    'total': 'Total',
    'email': 'Email',
    'phone': 'Phone Number',
    'available': 'Available',
    'occupied': 'Occupied',
    'selected': 'Selected',
    'payment': 'Payment',
    'card.number': 'Card Number',
    'expiry.date': 'Expiry Date',
    'cardholder.name': 'Cardholder Name',
    'booking.confirmed': 'Booking Confirmed!',
    'ticket.booked.successfully': 'Your ticket has been booked successfully. You will receive a confirmation message shortly.',
    'booking.reference': 'Booking Reference',
    'scan.at.station': 'Scan at station',
    'whatsapp.us': 'WhatsApp Us',
    'secure.payment.guaranteed': 'Secure Payment Guaranteed',
    'view.my.trips': 'View My Trips',
    'book.another.trip': 'Book Another Trip',
    'next': 'Next',
    'previous': 'Previous',
    
    // Dashboard
    'my.trips': 'My Trips',
    'upcoming': 'Upcoming',
    'past': 'Past',
    'download.ticket': 'Download Ticket',
    'cancel.trip': 'Cancel Trip',
    'reschedule': 'Reschedule',
    'welcome.back': 'Welcome back',
    'no.upcoming.trips': 'No upcoming trips',
    'no.past.trips': 'No past trips',
    'e.ticket': 'E-Ticket',
    'scan.qr.code': 'Scan QR code at the station',
    'booking.ref': 'Booking Ref:',
    'train': 'Train:',
    'seat': 'Seat:',
    'download.pdf': 'Download PDF',
    
    // Admin Panel
    'admin.dashboard': 'Admin Dashboard',
    'manage.train.booking.system': 'Manage Train Booking System',
    'overview': 'Overview',
    'trains': 'Trains',
    'bookings': 'Bookings',
    'users': 'Users',
    'total.bookings': 'Total Bookings',
    'total.revenue': 'Total Revenue',
    'active.trains': 'Active Trains',
    'total.users': 'Total Users',
    'recent.activity': 'Recent Activity',
    'new.booking': 'New Booking',
    'payment.received': 'Payment Received',
    'train.schedule.updated': 'Train Schedule Updated',
    'new.user.registration': 'New User Registration',
    'train.routes': 'Train Routes',
    'add.route': 'Add Route',
    'schedule': 'Schedule',
    'capacity': 'Capacity',
    'actions': 'Actions',
    'recent.bookings': 'Recent Bookings',
    'confirmed': 'Confirmed',
    'cancelled': 'Cancelled',
    'user.management': 'User Management',
    'joined': 'Joined:',
    'trips': 'trips',
    'access.denied': 'Access Denied',
    'no.permission': 'You do not have permission to access this area.',
    
    // Common
    'loading': 'Loading...',
    'error': 'Error',
    'success': 'Success',
    'cancel': 'Cancel',
    'confirm': 'Confirm',
    'save': 'Save',
    'edit': 'Edit',
    'delete': 'Delete',
    'submit': 'Submit',
    'back': 'Back',
    'close': 'Close',
    'select': 'Select',
    'min': 'Min',
    'max': 'Max',
    'minutes.ago': 'minutes ago',
    'hour.ago': 'hour ago',
    'hours.ago': 'hours ago',
    
    // Cities and Places
    'atbara.rail': 'Atbara Rail',
    'khartoum': 'Khartoum',
    'atbara': 'Atbara',
    'port.sudan': 'Port Sudan',
    'kassala': 'Kassala',
    'wad.medani': 'Wad Medani',
    'nyala': 'Nyala',
    'el.obeid': 'El Obeid',
    'dongola': 'Dongola',
    'sennar': 'Sennar',
    
    // Nationalities
    'sudan': 'Sudan',
    'egypt': 'Egypt',
    'ethiopia': 'Ethiopia',
    'eritrea': 'Eritrea',
    'chad': 'Chad',
    'libya': 'Libya',
    'south.sudan': 'South Sudan',
    'other': 'Other',
    
    // Train Classes
    'economy': 'Economy',
    'business': 'Business',
    'vip': 'VIP',
    
    // Currency
    'sdg': 'SDG'
  }
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<'ar' | 'en'>('en');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      <div className={language === 'ar' ? 'rtl' : 'ltr'} dir={language === 'ar' ? 'rtl' : 'ltr'}>
        {children}
      </div>
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};